### PR TITLE
v4 API: Legacy Resources

### PR DESCRIPTION
**Pull request by n7studios**
## Summary

Reinstates tests for legacy forms and landing pages, using the `v4-api` WordPress Libraries that now [fetch legacy resources](https://github.com/ConvertKit/convertkit-wordpress-libraries/pull/66).

## Testing

- Legacy resource tests previously marked as incomplete are reinstated.

## Checklist

* [x] I have [written a test](TESTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](TESTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](TESTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](DEVELOPMENT.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](DEVELOPMENT.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

### CODE REVIEW

**Review by noelherrick — COMMENTED** [review]
@mercedesb Tim is proposing caching legacy forms on client's WordPress sites since APIv4 won't return legacy forms. Is that correct? Are there plans to include them later, or was that deliberate decision to deprecate them.

Tim, we might need to hold off from moving wholly to the V4 API because I don't know how workable locally caching legacy forms is going to be unless we drop support for legacy forms, in which case I don't think we should be caching them either. This seems like a recipe for an inconsistent user experience.

**Comment by mercedesb** [comment]
> was that deliberate decision to deprecate them

Yes, it was a deliberate decision to deprecate legacy landing pages that [Marc and Megan made](https://github.com/ConvertKit/convertkit/pull/24622#discussion_r1277887252) and made sense in the long-term with where we want to get to eventually

**Comment by noelherrick** [comment]
@n7studios We will be adding another endpoint for legacy forms. We'll keep you posted when that's ready to use!

**Comment by n7studios** [comment]
> Tim, we might need to hold off from moving wholly to the V4 API because I don't know how workable locally caching legacy forms is going to be unless we drop support for legacy forms, in which case I don't think we should be caching them either. This seems like a recipe for an inconsistent user experience.

Apologies, I thought I'd replied to this.  That's fine - the v4 work merges into its own `v4-api` branch, so it doesn't affect other work and bugfixes that I'm doing for the current Plugin. 

> @n7studios We will be adding another endpoint for legacy forms. We'll keep you posted when that's ready to use!

Thanks. I'll look to implement this when ready, which will probably make this PR redundant.

**Review by noelherrick — APPROVED** [review]

**Pull request merged**
